export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_AUTO_LOGIN = 'AUTH_AUTO_LOGIN';

export const CUSTOMERS_FETCH_START = 'CUSTOMERS_FETCH';
export const CUSTOMERS_FETCH_SUCCESS = 'CUSTOMERS_FETCH_SUCCESS';
export const CUSTOMERS_FETCH_FAIL = 'CUSTOMERS_FETCH_FAIL';
export const CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE';
export const CUSTOMERS_UPDATE_SUCCESS = 'CUSTOMERS_UPDATE_SUCCESS';
export const CUSTOMERS_DELETE = 'CUSTOMERS_DELETE';
export const CUSTOMERS_DELETE_SUCCESS = 'CUSTOMERS_DELETE_SUCCESS';
export const CUSTOMERS_CREATE = 'CUSTOMERS_CREATE';